USE app_db;

CREATE TABLE posts
(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_id INT(6) NOT NULL,
    title VARCHAR(255) NOT NULL, 
    body TEXT NOT NULL, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);